In [1]:
import numpy as np

In [4]:
b = np.load('aspirin_dft.npz')

In [5]:
lst = b.files
for item in lst:
    print(item)
    print(b[item])

E
[[-406757.59126402]
 [-406757.03429293]
 [-406755.65420705]
 ...
 [-406738.25114808]
 [-406737.89506248]
 [-406738.57754977]]
name
b'aspirin'
F
[[[-1.83422357e+00  1.02434225e+00 -2.25436760e+00]
  [-5.59121851e+00  3.30994792e+00 -4.35124181e+00]
  [ 1.04185667e+01  1.81676621e+00  3.05341666e+00]
  ...
  [ 3.95919976e-01 -6.12724635e+00 -1.13366853e+00]
  [ 2.08211389e+00  9.96756689e-01  4.03806388e+00]
  [-5.99569827e+00 -2.13766450e+00 -7.17989220e+00]]

 [[-1.04133027e+00 -2.61586473e+00 -1.50520596e+00]
  [-2.81302853e+00 -1.40639243e+01 -2.23788628e+00]
  [ 1.42362686e+01  3.80961548e+00  5.24739971e+00]
  ...
  [ 7.25944458e-01 -3.82422526e+00 -3.96092177e-01]
  [ 2.27800376e+00 -2.35154405e+00  4.84802549e+00]
  [-6.10612008e+00 -2.54870388e+00 -1.19784380e+01]]

 [[ 1.24997471e-01 -6.79755526e+00 -5.67560326e-01]
  [-5.43891273e-01 -2.97347590e+01  1.03075665e-02]
  [ 1.78276993e+01  5.71814292e+00  7.43739052e+00]
  ...
  [ 1.20685534e+00 -1.12090880e+00  2.85009011e-01]


In [6]:
for i in lst:
    print(b[i])

[[-406757.59126402]
 [-406757.03429293]
 [-406755.65420705]
 ...
 [-406738.25114808]
 [-406737.89506248]
 [-406738.57754977]]
b'aspirin'
[[[-1.83422357e+00  1.02434225e+00 -2.25436760e+00]
  [-5.59121851e+00  3.30994792e+00 -4.35124181e+00]
  [ 1.04185667e+01  1.81676621e+00  3.05341666e+00]
  ...
  [ 3.95919976e-01 -6.12724635e+00 -1.13366853e+00]
  [ 2.08211389e+00  9.96756689e-01  4.03806388e+00]
  [-5.99569827e+00 -2.13766450e+00 -7.17989220e+00]]

 [[-1.04133027e+00 -2.61586473e+00 -1.50520596e+00]
  [-2.81302853e+00 -1.40639243e+01 -2.23788628e+00]
  [ 1.42362686e+01  3.80961548e+00  5.24739971e+00]
  ...
  [ 7.25944458e-01 -3.82422526e+00 -3.96092177e-01]
  [ 2.27800376e+00 -2.35154405e+00  4.84802549e+00]
  [-6.10612008e+00 -2.54870388e+00 -1.19784380e+01]]

 [[ 1.24997471e-01 -6.79755526e+00 -5.67560326e-01]
  [-5.43891273e-01 -2.97347590e+01  1.03075665e-02]
  [ 1.78276993e+01  5.71814292e+00  7.43739052e+00]
  ...
  [ 1.20685534e+00 -1.12090880e+00  2.85009011e-01]
  [ 2.705

In [13]:
b['z']

array([6, 6, 6, 6, 6, 6, 6, 8, 8, 8, 6, 6, 8, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=uint8)

In [26]:
b['theory']

array('aims: PBE+TS, light tier 1', dtype='<U26')

In [19]:
b.files

['E', 'name', 'F', 'theory', 'R', 'z', 'type', 'md5']

In [22]:
type(b['E'])

numpy.ndarray